### PR TITLE
using \uXXXX to encode unicode string

### PR DESCRIPTION
**Pull request by tengattack**
Hi, I'm trying using \uXXXX to encode unicode string
It will be useful in non-English system.

Thanks.

### CODE REVIEW

**Comment by kessler** [comment]
Hi

Would it possible for you to include a test case for this?
Thank you very much for contributing!

Kessler

**Comment by tengattack** [comment]
@kessler hi, I try add some non-English characters to the tests
Are these enough for the JSON Unicode encode test?

teng

**Comment by tengattack** [comment]
If I remove the JsonU function, the test will failed like this:

failed message

**Comment by kessler** [comment]
I just tested it and its ok! :+1:

**Pull request merged**
